Develop to main
JackobTheLion/java-filmorate pull request #20
Opened 2023-05-29 06:43 UTC by JackobTheLion

2023-05-29 06:54 UTC, FokuZz approved these changes

2023-05-29 23:00 UTC, FokuZz submitted a review, later dismissed

2023-05-30 12:50 UTC, YazykovMikhail requested changes

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review addReview(HttpServletRequest request, @NotNull @Valid @RequestBody Review review) {
HttpServletRequest request особого смысла принимать нет. Это только награмождает метод и приходится разбиратся для чего он, а он только для логирвоания. 
Проще руками прописать логи. 
И так же вы пишите 1 проект, т.е ваш код должен быть как минимум похожим, а в идеале единообразным. 
Поэтому лучше сделать как в других контроллерах. 
Убрать HttpServletRequest request из параметров методов

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findPopularFilms(@RequestParam(required = true, defaultValue = "10") String query,
если параметр обязательный то зачем тут значение по умолчанию?
Если придет null то должна бывть ошибка. Либо параметр не долже быть обяаетльным

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private final Set<Long> friends = new HashSet<>();
в этом поле уже нет смысла. Он нужен был когда хранили данные в Map. 
теперь вы храните данные в БД, а для работы с друзьями есть отдельные эндпоинты

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        directorStorage.getDirector(id);
В такой проверке не совсме есть смысл. ЛУчше ее убрать. Она была хоть как то оравдана для Map. Но для бд нет. 
Нет и нет. Если уже пользователя нет, то и уадалять нечего.

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        directorStorage.getDirector(director.getId());
Я бы скзаал что и тут проверка не нужна. Т.е если такого пользователя нет, он просто не обновится. Новый не добавится, ведь это не Map где при "обновлении" добавляется новый полтзователь. 

А любой запрос к БД это трудоемкое дело. Потому что нужно создавать подклчюение и потом его закрывать. Стоит избегать лишних запросов.

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        log.info("Class: {}. Method: addReview. Obj: {}", ReviewService.class, review);
зачем логировать класс  ReviewService.class?
Логирвоание нужно что бы при ошибке можно было отследить что происходило и какие было данные, в логировании класса смысла нет. 

Так же обратите внимание что этот лог повторяет лог из контролелра. Но что за это время поменялось? ничего. Тогда зачем он? Но вот логирвоания ответа нет. А как тогда узнать что вернулось по результатм запроса? Никак. 
Избавьтесь от повторного логирвоания в коде. И добавьте логирвоания ответов (или в серсиве или в котроллере)

Логи должны быть передавать занчемые вещи.
1) какой запрос с каки данным ипришел
2) Какие данные у менялись в процессе выполнения
3) Что отправилось в ответ

Это вот минимум который должен быть в логах, что бы потом оследить что происхоидло

2023-05-30 12:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Likes.java
> +public class Likes {
Вообще конечно модель для таблиц многие ко многим обычно не далется. 
Делается или запрос например за пользователями по id фильма и поулуется сразу в ответ все пользователи кому понравился фильм. 
Или просто возвращется список id пользователей если толкьо он нужен (List<Long>)
А возвращать идентификаторы многие ко многим а потом делать по ним еще один запрос , особого смысла нет. Можно же сразу написать запрос который вернет всех пользвоателей. Или всех id пользоватлей ввиде списка. Смотря что нужно

2023-05-31 19:56 UTC, merged

2023-06-02 09:14 UTC, bismuthD reviewed
Отличная работа, очень качественный ход, хорошо разобрались со взаимодействием между слоями сервис контроллер репозиторий, везде использованы верные аннотации, модификаторы доступа. Оставил только один комментарий для улучшения кода

2023-06-02 09:14 UTC, bismuthD commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    private final Long timestamp;
Вместо множественных private лучше использовать @FieldDefaults