Add database
JackobTheLion/java-filmorate pull request #9
Opened 2023-04-26 12:42 UTC by JackobTheLion

2023-04-26 15:28 UTC, YazykovMikhail requested changes

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (filmId <= 0 || userId <= 0) {
Если делаешь ручную вадлидацю, вынеси ее лучше в сервис. 
Поправь везде

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +  rating Integer REFERENCES mpa (mpa_id) ON DELETE CASCADE
Это поле это mpa_id
а rate - это отдельное поле. 
Можно сделать поле rate которое булет увеличиваеться от проставленных лайков.

Типо вот так:


```
@Override
	public void addLike(long filmId, long userId) {
		String sqlQuery = "merge into LIKES (film_id, user_id) values (?, ?)";
		jdbcTemplate.update(sqlQuery, filmId, userId);
		updateRate(filmId);
	}

	private void updateRate(long filmId) {
		String sqlQuery = "update FILMS f set rate = (select count(l.user_id) from LIKES l where l.film_id = f.film_id)  where film_id = ?";
		jdbcTemplate.update(sqlQuery, filmId);
	}
```

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Qualifier("dbStorage")
Ну сервисы у нас вроде в одном экземляре, тем бодее у сервис нет интерфейсов, так что для них @Qualifier не особо актуален. 
Для сервисов убери

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/RatingService.java
> +@Qualifier("dbStorage")
ЛУчше давать разные названия.
Ведь интерфейс может быть и одтн на всех.

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    private final RatingStorage ratingStorage;
ЛУчше из одного стораджа в другой не ходить. 
Если нужно сходить, ходи из сервиса в другой сторадж. 
Лишние зависимости всегда не очень. Тем более дело если ыт к ним обращаешься получается делается несколько запросов, а этого стоит избегать если это овзможно. Потому что подключение к БД требует определенных ресурсов. Все что можно извлечь одним запросом, лучше извлекать одним запросом.

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        String sql = "SELECT * FROM films f JOIN mpa m ON f.rating = m.mpa_id WHERE film_id = ?";
Вот тут ты делалешь join для mpa и это верно. Так нужно делать везде тогда RatingStorage ratingStorage будет не нужен
Поправь везде

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/rating/DbRatingStorage.java
> +public class DbRatingStorage implements RatingStorage {
DbMpaStorage

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public void addLike(Long filmId, Long userId) {
Для лайков есть своя БД, тут эти методы вообще не нужны

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void removeLike(Long filmId, Long userId) {
Это тут не нужно
Это Сторадж отвечающий за фильмы. Для лайков есть свой.

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public List<Film> getPopularFilms(Integer limit) {
Это метод тоже лучше вынести в лайки

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    private final GenreStorage genreStorage;
С жанрами сожнее, потому что 1 ко многим. 
Но в любом случае из DbFilmStorage в GenreStorage мы не образаемся. 
Выносим ображение в сервис. 
Т.е ты получаешь фильмы без жанров, а потом из сервиса вызываешь запрос для получения жанров и заполняешь фильмы жанрами.

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DbUserStorage.java
> +        String sql = "INSERT INTO filmorate_users (email, login, name, birthday) VALUES (?,?,?,?)";
не используется

2023-04-26 15:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +public class RatingController {
MpaController

2023-04-28 09:09 UTC, JackobTheLion commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        String sql = "SELECT * FROM films f JOIN mpa m ON f.rating = m.mpa_id WHERE film_id = ?";
По ТЗ есть эндпоинты  GET /mpa и GET /mpa/{id}, поэтому, возможно, RatingStorage стоит оставить

2023-05-02 08:39 UTC, merged